Repository ZeroWastePlatform/BackEnd, pull requests merged in 2022-12, with the labels that each got.

#3 Feat: Swagger 연동 및 패키지 구조 개선
  build.gradle
  src/main/java/com/greenUs/server/domain/post/api/SwaggerTestController.java
  src/main/java/com/greenUs/server/domain/post/dto/User.java
  src/main/java/com/greenUs/server/global/config/SwaggerConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 기능, 개선

#6 Feat: domain setting
  build.gradle
  src/main/java/com/greenUs/server/attachment/domain/Attachment.java
  src/main/java/com/greenUs/server/attachment/repository/AttachmentRepository.java
  src/main/java/com/greenUs/server/basket/domain/Basket.java
  src/main/java/com/greenUs/server/basket/repository/BasketRepository.java
  src/main/java/com/greenUs/server/bookmark/domain/Bookmark.java
  src/main/java/com/greenUs/server/bookmark/repository/BookmarkRepository.java
  src/main/java/com/greenUs/server/comment/domain/Comment.java
  src/main/java/com/greenUs/server/comment/repository/CommentRepository.java
  src/main/java/com/greenUs/server/common/BaseEntity.java
  src/main/java/com/greenUs/server/delivery/domain/Delivery.java
  src/main/java/com/greenUs/server/delivery/repository/DeliveryRepository.java
  src/main/java/com/greenUs/server/domain/post/dto/User.java
  src/main/java/com/greenUs/server/hashtag/domain/Hashtag.java
  src/main/java/com/greenUs/server/hashtag/domain/PostHashtag.java
  src/main/java/com/greenUs/server/hashtag/repository/HashtagRepository.java
  src/main/java/com/greenUs/server/member/domain/Member.java
  src/main/java/com/greenUs/server/member/domain/SocialType.java
  src/main/java/com/greenUs/server/member/repository/MemberRepository.java
  src/main/java/com/greenUs/server/order/domain/Order.java
  src/main/java/com/greenUs/server/order/repository/OrderRepository.java
  src/main/java/com/greenUs/server/post/controller/SwaggerTestController.java
  src/main/java/com/greenUs/server/post/domain/Post.java
  src/main/java/com/greenUs/server/post/dto/User.java
  src/main/java/com/greenUs/server/post/repository/PostRepository.java
  src/main/java/com/greenUs/server/product/domain/OrderProduct.java
  src/main/java/com/greenUs/server/product/domain/Product.java
  src/main/java/com/greenUs/server/product/repository/ProductRepository.java
  src/main/resources/application.yml
Labels: 백엔드, 구조

#11 Feature/post-crud
  src/main/java/com/greenUs/server/ServerApplication.java
  src/main/java/com/greenUs/server/member/domain/Member.java
  src/main/java/com/greenUs/server/post/controller/PostController.java
  src/main/java/com/greenUs/server/post/domain/Post.java
  src/main/java/com/greenUs/server/post/dto/PostRequestDto.java
  src/main/java/com/greenUs/server/post/dto/PostResponseDto.java
  src/main/java/com/greenUs/server/post/repository/PostRepository.java
  src/main/java/com/greenUs/server/post/service/PostService.java
  src/main/resources/application.yml
  src/test/java/com/greenUs/server/post/service/PostServiceTest.java
Labels: 기능, 개선, 백엔드
