Repository ZeroWastePlatform/BackEnd, pull requests merged in 2023-01, with the labels that each got.

#13 chore: add deploy setting files
  Procfile
  system.properties
Labels: 중요

#15 Feature/oauth login
  build.gradle
  src/main/java/com/greenUs/server/auth/application/OAuthClient.java
  src/main/java/com/greenUs/server/auth/application/OAuthUri.java
  src/main/java/com/greenUs/server/auth/controller/AuthCodeController.java
  src/main/java/com/greenUs/server/auth/controller/AuthController.java
  src/main/java/com/greenUs/server/auth/dto/OAuthMember.java
  src/main/java/com/greenUs/server/auth/dto/request/TokenRequest.java
  src/main/java/com/greenUs/server/auth/dto/response/AccessRefreshTokenResponse.java
  src/main/java/com/greenUs/server/auth/dto/response/OAuthAccessTokenResponse.java
  src/main/java/com/greenUs/server/auth/dto/response/OAuthUriResponse.java
  src/main/java/com/greenUs/server/global/config/PropertiesConfig.java
  src/main/java/com/greenUs/server/global/config/properties/GoogleProperties.java
  src/main/java/com/greenUs/server/infrastructure/oauth/client/GoogleOAuthClient.java
  src/main/java/com/greenUs/server/infrastructure/oauth/dto/GoogleTokenResponse.java
  src/main/java/com/greenUs/server/infrastructure/oauth/dto/UserInfo.java
  src/main/java/com/greenUs/server/infrastructure/oauth/exception/OAuthException.java
  src/main/java/com/greenUs/server/infrastructure/oauth/uri/GoogleOauthUri.java
  src/main/resources/application-dev.yml
Labels: 백엔드

#17 Feature/hashtag
  src/main/java/com/greenUs/server/hashtag/domain/Hashtag.java
  src/main/java/com/greenUs/server/hashtag/domain/Keyword.java
  src/main/java/com/greenUs/server/hashtag/domain/PostHashtag.java
  src/main/java/com/greenUs/server/hashtag/repository/HashtagRepository.java
  src/main/java/com/greenUs/server/hashtag/repository/KeywordRepository.java
  src/main/java/com/greenUs/server/hashtag/service/HashtagService.java
  src/main/java/com/greenUs/server/hashtag/service/KeywordService.java
  src/main/java/com/greenUs/server/post/controller/PostController.java
  src/main/java/com/greenUs/server/post/controller/SwaggerTestController.java
  src/main/java/com/greenUs/server/post/domain/Post.java
  src/main/java/com/greenUs/server/post/dto/PostRequestDto.java
  src/main/java/com/greenUs/server/post/dto/PostResponseDto.java
  src/main/java/com/greenUs/server/post/dto/User.java
  src/main/java/com/greenUs/server/post/service/PostService.java
  src/main/resources/application-db.yml
Labels: 기능, 백엔드

#22 Feature/update user info
  src/main/java/com/greenUs/server/auth/application/AuthService.java
  src/main/java/com/greenUs/server/auth/dto/OAuthMember.java
  src/main/java/com/greenUs/server/member/controller/MemberController.java
  src/main/java/com/greenUs/server/member/domain/Member.java
  src/main/java/com/greenUs/server/member/dto/request/MemberRequest.java
  src/main/java/com/greenUs/server/member/dto/response/MemberResponse.java
  src/main/java/com/greenUs/server/member/exception/InvalidMemberException.java
  src/main/java/com/greenUs/server/member/service/MemberService.java
  src/main/java/com/greenUs/server/review/domain/Review.java
Labels: 기능, 백엔드

#25 Feature/authentication principal
  src/main/java/com/greenUs/server/auth/application/AuthService.java
  src/main/java/com/greenUs/server/auth/application/AuthTokenCreator.java
  src/main/java/com/greenUs/server/auth/application/TokenCreator.java
  src/main/java/com/greenUs/server/auth/controller/AuthController.java
  src/main/java/com/greenUs/server/auth/controller/AuthenticationPrincipal.java
  src/main/java/com/greenUs/server/auth/controller/AuthenticationPrincipalArgumentResolver.java
  src/main/java/com/greenUs/server/auth/dto/LoginMember.java
  src/main/java/com/greenUs/server/auth/exception/EmptyAuthorizationHeaderException.java
  src/main/java/com/greenUs/server/global/config/WebConfig.java
  src/main/java/com/greenUs/server/member/controller/MemberController.java
  src/main/java/com/greenUs/server/member/dto/request/MemberRequest.java
  src/main/java/com/greenUs/server/member/exception/InvalidMemberException.java
  src/main/java/com/greenUs/server/member/exception/NotExistMemberException.java
  src/main/java/com/greenUs/server/member/exception/NotFoundMemberException.java
  src/main/java/com/greenUs/server/member/service/MemberService.java
Labels: 기능, 백엔드

#29 Feature/search
  src/main/java/com/greenUs/server/post/controller/PostController.java
  src/main/java/com/greenUs/server/post/repository/PostRepository.java
  src/main/java/com/greenUs/server/post/service/PostService.java
Labels: 기능, 백엔드

#30 Test: member
  src/main/java/com/greenUs/server/member/dto/request/MemberRequest.java
  src/test/java/com/greenUs/server/member/repository/MemberRepositoryTest.java
  src/test/java/com/greenUs/server/member/service/MemberServiceTest.java
  src/test/resources/application-test.yml
Labels: 테스트
