Repository ZeroWastePlatform/BackEnd, pull requests merged in 2023-03, with the labels that each got.

#57 Refactor: class method name
  src/main/java/com/greenUs/server/comment/controller/CommentController.java
  src/main/java/com/greenUs/server/comment/dto/CommentRequest.java
  src/main/java/com/greenUs/server/comment/dto/CommentResponse.java
  src/main/java/com/greenUs/server/comment/repository/CommentRepository.java
  src/main/java/com/greenUs/server/comment/service/CommentService.java
  src/main/java/com/greenUs/server/global/Time.java
  src/main/java/com/greenUs/server/hashtag/controller/HashtagController.java
  src/main/java/com/greenUs/server/hashtag/domain/Hashtag.java
  src/main/java/com/greenUs/server/hashtag/domain/Keyword.java
  src/main/java/com/greenUs/server/hashtag/dto/HashtagResponse.java
  src/main/java/com/greenUs/server/hashtag/service/HashtagService.java
  src/main/java/com/greenUs/server/member/controller/MemberController.java
  src/main/java/com/greenUs/server/member/dto/response/MyPageCommunityResponse.java
  src/main/java/com/greenUs/server/member/service/MemberService.java
  src/main/java/com/greenUs/server/post/controller/PostController.java
  src/main/java/com/greenUs/server/post/dto/PostPopularityResponse.java
  src/main/java/com/greenUs/server/post/dto/PostRecommendationResponse.java
  src/main/java/com/greenUs/server/post/dto/PostRequest.java
  src/main/java/com/greenUs/server/post/dto/PostResponse.java
  src/main/java/com/greenUs/server/post/repository/PostRepository.java
  src/main/java/com/greenUs/server/post/service/PostService.java
Labels: 리팩토링

#58 Docs: auth swagger
  build.gradle
  src/main/java/com/greenUs/server/auth/application/AuthService.java
  src/main/java/com/greenUs/server/auth/controller/AuthController.java
Labels: 백엔드, 스웨거

#65 Update: generateAccessTokenRefreshToken 응답값 변환
  src/main/java/com/greenUs/server/auth/application/AuthService.java
  src/main/java/com/greenUs/server/auth/controller/AuthController.java
  src/main/java/com/greenUs/server/auth/dto/response/AccessRefreshTokenResponse.java
Labels: 기능, 백엔드

#70 Fix: 게시글 작성 에러부분 해결
  src/main/java/com/greenUs/server/post/controller/PostController.java
  src/main/java/com/greenUs/server/post/dto/PostRequest.java
  src/main/java/com/greenUs/server/post/service/PostService.java
Labels: 개선, 테스트

#75 Feature: thumbnail
  build.gradle
  src/main/java/com/greenUs/server/attachment/domain/Attachment.java
  src/main/java/com/greenUs/server/attachment/exception/FailResizeAttachment.java
  src/main/java/com/greenUs/server/attachment/repository/AttachmentRepository.java
  src/main/java/com/greenUs/server/attachment/service/AttachmentService.java
  src/main/java/com/greenUs/server/comment/controller/CommentController.java
  src/main/java/com/greenUs/server/comment/dto/CommentResponse.java
  src/main/java/com/greenUs/server/comment/service/CommentService.java
  src/main/java/com/greenUs/server/global/error/ErrorCode.java
  src/main/java/com/greenUs/server/global/error/GlobalExceptionHandler.java
  src/main/java/com/greenUs/server/hashtag/controller/HashtagController.java
  src/main/java/com/greenUs/server/hashtag/service/HashtagService.java
  src/main/java/com/greenUs/server/member/dto/response/MyPageCommunityResponse.java
  src/main/java/com/greenUs/server/member/service/MemberService.java
  src/main/java/com/greenUs/server/post/controller/PostController.java
  src/main/java/com/greenUs/server/post/domain/Post.java
  src/main/java/com/greenUs/server/post/dto/request/PostRequest.java
  src/main/java/com/greenUs/server/post/dto/response/CommunityMemberResponse.java
  src/main/java/com/greenUs/server/post/dto/response/MyPageCommentResponse.java
  src/main/java/com/greenUs/server/post/dto/response/MyPagePostResponse.java
  src/main/java/com/greenUs/server/post/dto/response/PostDetailResponse.java
  src/main/java/com/greenUs/server/post/dto/response/PostListsResponse.java
  src/main/java/com/greenUs/server/post/dto/response/PostPopularityResponse.java
  src/main/java/com/greenUs/server/post/dto/response/PostRecommendationResponse.java
  src/main/java/com/greenUs/server/post/service/PostService.java
Labels: 기능, 백엔드

#76 Feature: dynamic query
  build.gradle
  src/main/java/com/greenUs/server/global/config/JpaConfig.java
  src/main/java/com/greenUs/server/product/controller/ProductController.java
  src/main/java/com/greenUs/server/product/converter/ProductStatusConverter.java
  src/main/java/com/greenUs/server/product/domain/Product.java
  src/main/java/com/greenUs/server/product/domain/ProductStatus.java
  src/main/java/com/greenUs/server/product/dto/Price.java
  src/main/java/com/greenUs/server/product/dto/ProductStatus.java
  src/main/java/com/greenUs/server/product/dto/request/ProductsRequest.java
  src/main/java/com/greenUs/server/product/dto/response/ProductsResponse.java
  src/main/java/com/greenUs/server/product/repository/ProductRepositoryCustom.java
  src/main/java/com/greenUs/server/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/greenUs/server/product/service/ProductService.java
Labels: 기능, 백엔드

#78 Update: MyPageProfileResponseDto에 memberId 추가
  src/main/java/com/greenUs/server/member/dto/response/MyPageProfileResponse.java
  src/main/java/com/greenUs/server/member/service/MemberService.java
Labels: 백엔드

#80 Refactor: comment DTO에 parentId 추가
  src/main/java/com/greenUs/server/comment/dto/CommentResponse.java
  src/main/java/com/greenUs/server/comment/exception/NotEqualCommentAndPostComment.java
  src/main/java/com/greenUs/server/comment/repository/CommentRepository.java
  src/main/java/com/greenUs/server/comment/service/CommentService.java
  src/main/java/com/greenUs/server/global/error/ErrorCode.java
  src/main/java/com/greenUs/server/global/error/GlobalExceptionHandler.java
Labels: 개선

#81 Update: Product thumbnail 추가
  src/main/java/com/greenUs/server/attachment/domain/Attachment.java
  src/main/java/com/greenUs/server/product/domain/Product.java
  src/main/java/com/greenUs/server/product/dto/response/ProductsResponse.java
  src/main/java/com/greenUs/server/product/service/ProductService.java
Labels: 백엔드

#83 Feature: product detail
  src/main/java/com/greenUs/server/auth/controller/AuthController.java
  src/main/java/com/greenUs/server/basket/controller/BasketController.java
  src/main/java/com/greenUs/server/comment/controller/CommentController.java
  src/main/java/com/greenUs/server/global/error/GlobalExceptionHandler.java
  src/main/java/com/greenUs/server/hashtag/controller/HashtagController.java
  src/main/java/com/greenUs/server/member/controller/MemberController.java
  src/main/java/com/greenUs/server/post/controller/PostController.java
  src/main/java/com/greenUs/server/product/controller/ProductController.java
  src/main/java/com/greenUs/server/product/domain/Product.java
  src/main/java/com/greenUs/server/product/dto/Order.java
  src/main/java/com/greenUs/server/product/dto/response/ProductDetailResponse.java
  src/main/java/com/greenUs/server/product/exception/NotFoundProductException.java
  src/main/java/com/greenUs/server/product/repository/ProductRepository.java
  src/main/java/com/greenUs/server/product/service/ProductService.java
  src/main/java/com/greenUs/server/reviewAndAsk/controller/ReviewCommandController.java
  src/main/java/com/greenUs/server/reviewAndAsk/controller/ReviewController.java
  src/main/java/com/greenUs/server/reviewAndAsk/controller/ReviewQueryController.java
  src/main/java/com/greenUs/server/reviewAndAsk/domain/Ask.java
  src/main/java/com/greenUs/server/reviewAndAsk/domain/Review.java
  src/main/java/com/greenUs/server/reviewAndAsk/dto/AskDto.java
  src/main/java/com/greenUs/server/reviewAndAsk/dto/GetAskDetailDto.java
  src/main/java/com/greenUs/server/reviewAndAsk/dto/GetReviewDetailDto.java
  src/main/java/com/greenUs/server/reviewAndAsk/dto/GetReviewDto.java
  src/main/java/com/greenUs/server/reviewAndAsk/dto/ReviewDto.java
  src/main/java/com/greenUs/server/reviewAndAsk/dto/response/AskResponse.java
  src/main/java/com/greenUs/server/reviewAndAsk/dto/response/ReviewResponse.java
  src/main/java/com/greenUs/server/reviewAndAsk/repository/AskRepository.java
  src/main/java/com/greenUs/server/reviewAndAsk/repository/ReviewRepository.java
  src/main/java/com/greenUs/server/reviewAndAsk/service/AskService.java
  src/main/java/com/greenUs/server/reviewAndAsk/service/ReviewCommandService.java
  src/main/java/com/greenUs/server/reviewAndAsk/service/ReviewQueryService.java
  src/main/java/com/greenUs/server/reviewAndAsk/service/ReviewService.java
Labels: 기능, 백엔드

#85 Feature: product like
  src/main/java/com/greenUs/server/global/error/ErrorCode.java
  src/main/java/com/greenUs/server/global/error/GlobalExceptionHandler.java
  src/main/java/com/greenUs/server/member/controller/MemberController.java
  src/main/java/com/greenUs/server/member/dto/response/MyPageLikeProductResponse.java
  src/main/java/com/greenUs/server/member/service/MemberService.java
  src/main/java/com/greenUs/server/product/controller/ProductController.java
  src/main/java/com/greenUs/server/product/domain/Product.java
  src/main/java/com/greenUs/server/product/domain/ProductLike.java
  src/main/java/com/greenUs/server/product/exception/LikeDuplicateException.java
  src/main/java/com/greenUs/server/product/repository/ProductLikeRepository.java
  src/main/java/com/greenUs/server/product/repository/ProductRepository.java
  src/main/java/com/greenUs/server/product/service/ProductService.java
Labels: 기능, 백엔드

#88 Refactor: 마이페이지 댓글 response 데이터 추가
  src/main/java/com/greenUs/server/member/dto/response/MyPageCommentResponse.java
  src/main/java/com/greenUs/server/member/dto/response/MyPageCommunityResponse.java
  src/main/java/com/greenUs/server/member/dto/response/MyPagePostResponse.java
  src/main/java/com/greenUs/server/member/service/MemberService.java
Labels: 구조, 리팩토링
