Repository ZeroWastePlatform/BackEnd, pull requests merged in 2023-04, with the labels that each got.

#90 Refactor: 이미지 로딩에 대한 CDN 적용
  src/main/java/com/greenUs/server/attachment/service/AttachmentService.java
Labels: 개선, 리팩토링

#93 Refactor: jpa annotation
  src/main/java/com/greenUs/server/auth/application/AuthService.java
  src/main/java/com/greenUs/server/auth/dto/OAuthMember.java
  src/main/java/com/greenUs/server/basket/domain/Basket.java
  src/main/java/com/greenUs/server/basket/service/BasketService.java
  src/main/java/com/greenUs/server/bookmark/domain/Bookmark.java
  src/main/java/com/greenUs/server/comment/domain/Comment.java
  src/main/java/com/greenUs/server/coupon/domain/Coupon.java
  src/main/java/com/greenUs/server/delivery/domain/Delivery.java
  src/main/java/com/greenUs/server/hashtag/domain/Keyword.java
  src/main/java/com/greenUs/server/member/controller/MemberController.java
  src/main/java/com/greenUs/server/member/domain/Address.java
  src/main/java/com/greenUs/server/member/domain/Member.java
  src/main/java/com/greenUs/server/member/dto/response/MyPagePurchaseResponse.java
  src/main/java/com/greenUs/server/member/repository/MemberRepository.java
  src/main/java/com/greenUs/server/member/service/MemberService.java
  src/main/java/com/greenUs/server/post/domain/Post.java
  src/main/java/com/greenUs/server/post/domain/Recommend.java
  src/main/java/com/greenUs/server/product/domain/Product.java
  src/main/java/com/greenUs/server/product/domain/ProductLike.java
  src/main/java/com/greenUs/server/purchase/domain/Purchase.java
  src/main/java/com/greenUs/server/purchase/domain/PurchaseProduct.java
  src/main/java/com/greenUs/server/purchase/dto/response/PurchaseResponse.java
  src/main/java/com/greenUs/server/purchase/repository/PurchaseProductRepository.java
  src/main/java/com/greenUs/server/purchase/repository/PurchaseRepository.java
  src/main/java/com/greenUs/server/purchase/service/PurchaseService.java
  src/main/java/com/greenUs/server/reviewAndAsk/domain/Ask.java
  src/main/java/com/greenUs/server/reviewAndAsk/domain/Review.java
Labels: 백엔드, 리팩토링

#95 Refactor: 오늘의 인기글 추가 데이터 반환
  src/main/java/com/greenUs/server/post/controller/PostController.java
  src/main/java/com/greenUs/server/post/service/PostService.java
Labels: 개선, 리팩토링

#96 Feature: refresh token redis
  .gitignore
  build.gradle
  src/main/java/com/greenUs/server/auth/application/AuthService.java
  src/main/java/com/greenUs/server/auth/application/AuthTokenCreator.java
  src/main/java/com/greenUs/server/auth/application/TokenCreator.java
  src/main/java/com/greenUs/server/auth/controller/AuthController.java
  src/main/java/com/greenUs/server/auth/controller/CookieProvider.java
  src/main/java/com/greenUs/server/auth/domain/RefreshToken.java
  src/main/java/com/greenUs/server/auth/dto/OAuthMember.java
  src/main/java/com/greenUs/server/auth/exception/RefreshTokenNotExistException.java
  src/main/java/com/greenUs/server/auth/repository/RefreshTokenRepository.java
  src/main/java/com/greenUs/server/global/config/RedisConfig.java
  src/main/java/com/greenUs/server/global/error/ErrorCode.java
  src/main/java/com/greenUs/server/global/error/GlobalExceptionHandler.java
  src/main/java/com/greenUs/server/member/domain/Member.java
  src/main/resources/application-bucket.yml
  src/main/resources/application-db.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-security.yml
  src/main/resources/application.yml
Labels: 백엔드

#99 Feature: product-option
  src/main/java/com/greenUs/server/product/domain/ProductOption.java
  src/main/java/com/greenUs/server/product/dto/response/ProductDetailResponse.java
  src/main/java/com/greenUs/server/product/repository/ProductOptionRepository.java
  src/main/java/com/greenUs/server/product/service/ProductService.java
Labels: 기능, 개선
